= Integration Guides

Below are the guidelines and specifications for integrating any software development kit (SDK) with Inji Wallet:

 . The SDK should be available as an npm module for seamless integration with React Native applications.
* For Android, integration should be supported via a Maven dependency.
* For iOS, integration should be supported via Swift Package Manager (SPM).

    For example, the npm modules, [_tuvali_](https://www.npmjs.com/package/@mosip/tuvali) and [_secure-keystore_](https://www.npmjs.com/package/@mosip/secure-keystore)_,_ demonstrate suitable implementations.
.  The SDK should provide simple APIs for integration purposes.

    These APIs should include an API for instantiation or initialization, such as the _init_ or _constructor_ API.
. The SDK should also include additional APIs that perform the necessary actions.
.  There should be an API available to _disconnect_ the SDK, if needed.

    If possible, it would be beneficial for these APIs to be _asynchronous_. This enables users to continue using the application without experiencing any UI blocking.
. To enhance logging and traceability, the API may accept an optional parameter known as `traceabilityId`.

By adhering to these specifications, the integrated SDK will enhance the functionality and usability of the application.

This section contains various guides and information that could benefit the developers, system integrators, relying parties and end users.

For more information on how to get started with integrations, read through:

. Secure Keystore
. PixelPass
. Tuvali - Sharing via BLE
. OpenID4VP - Online Sharing SDK
. Face Match
. BLE Verifier
. Telemetry (details coming soon)


<table data-view="cards"><thead><tr><th></th><th></th><th></th><th data-hidden data-card-cover data-type="files"></th><th data-hidden data-card-target data-type="content-ref"></th></tr></thead><tbody><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/Tuvali (2).png">Tuvali (2).png</a></td><td><a href="tuvali/">tuvali</a></td></tr><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/Face Match.png">Face Match.png</a></td><td><a href="face-match.md">face-match.md</a></td></tr><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/ble-verifier.png">ble-verifier.png</a></td><td><a href="ble-verifier.md">ble-verifier.md</a></td></tr><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/background - Copy (3).png">background - Copy (3).png</a></td><td><a href="secure-keystore.md">secure-keystore.md</a></td></tr><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/PixelPass.png">PixelPass.png</a></td><td><a href="pixelpass.md">pixelpass.md</a></td></tr><tr><td></td><td></td><td></td><td><a href="../../.gitbook/assets/Telemetry.png">Telemetry.png</a></td><td><a href="telemetry.md">telemetry.md</a></td></tr></tbody></table>


